# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170604_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
